# Generated by Django 2.1.7 on 2021-06-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210629_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 6, 29, 14, 2, 22, 545768)),
        ),
    ]
